### ISSUE TITLE
Declaration of ...

### ISSUE THREAD

**Issue by karnok** [LavaLite/cms#305]
After sudo php artisan lavalite:install and php artisan key:generate
I got error:
ErrorException (E_WARNING)
Declaration of Litepie\Repository\Eloquent\BaseRepository::count() should be compatible with Prettus\Repository\Eloquent\BaseRepository::count(array $where = Array, $columns = '*')

From /vendor/lavalite/framework/src/Litepie/Repository/Eloquent/BaseRepository.php

Ubuntu 16.04 With Apache2, MariaDB And PHP 7.2

**Comment by karnok** [comment]
![error](https://user-images.githubusercontent.com/12460052/64266913-1e03d380-cf3e-11e9-9473-6131cb6d3001.png)

**Comment by itanea** [comment]
I have the same. At the beginning, I think it was my Homestead installation occurs this error but with an installation on Laragon, this is the same.

**Comment by charliex2** [comment]
I have the same. Does anyone have solutions?

**Comment by Renfos** [comment]
Fixed the issue.
Run `composer update` and try again

**Comment by itanea** [comment]
I launch the update and I get this :
![image](https://user-images.githubusercontent.com/425998/64472511-f9874180-d15f-11e9-875a-6a58a8ca586d.png)

php artisan cli and website are broken now :-(

**Comment by itanea** [comment]
I'm investigating ;-)

**Comment by karnok** [comment]
Please reopen the problems. you did not solve it, but made it worse

> Fixed the issue.
> Run `composer update` and try again

Please reopen the issue. 
You did not solve it, but made it worse.

**Comment by itanea** [comment]
> > Fixed the issue.
> > Run `composer update` and try again
> 
> Please reopen the issue.
> You did not solve it, but made it worse.

I agree !! :D

**Comment by itanea** [comment]
please @Renfos can you reopen this bug and help us ;-)

**Comment by itanea** [comment]
Thanks @Renfos .
Hope you can fix this easily ;-)

**Comment by Renfos** [comment]
it is fixed.
Run 'composer update` and try

**Comment by lukeyMing** [comment]
its not fixed

**Comment by farkas87** [comment]
i solved it by making the BaseRepository::count method compatible with the one of Prettus, by changing its signature like this:

public function count(array $where = [], $columns = ['id'])

**Comment by ZeroSum000** [comment]
This issues seems to be happening again but I can not find where to make this edit. Is there any further guidance available on this issue?
